---
- name: debian | installing pre-reqs
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - acl
    - dnsutils
    - krb5-user
    - krb5-config
    - python-glade2
    - samba
    - samba-common
#    - smbclient
    - smbldap-tools
    - system-config-samba
    - winbind
    - libpam-winbind
    - libnss-winbind
