---
- name: redhat | installing pre-reqs
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - krb5-workstation
    - samba-winbind
    - samba-winbind-clients
    - authconfig
    - samba-client

